/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:29636d01-ad44-4483-88df-28381b0de99e",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_8UYMLVQ6g",
    "aws_user_pools_web_client_id": "3s1t86lckteq5ebf5lkt6c5o13",
    "oauth": {}
};


export default awsmobile;
